import { User, UserDocument } from '../../../modules/user/entities/user.entity';
import { AdminUser, AdminUserDocument } from '../../../modules/admin-users/entities/admin-user.entity';
import { IAdminUser } from '../../../common/interfaces/admin-user.interface';
import { Lead, LeadDocument } from '../../../modules/leads/entity/lead.entity';
import { ILead } from '../../../common/interfaces/leads.interface';
import { Cart, CartDocument } from '../../../modules/cart/entities/cart.entity';
import { Order, OrderDocument } from '../../../modules/orders/entities/order.entity';
import { Address, AddressDocument } from '../../../modules/address/entities/address.entity';
import { IUser } from '../../../common/interfaces/user.interface';
import { ICart } from '../../../common/interfaces/cart.interface';
import { IOrder } from '../../../common/interfaces/order.interface';
import { IAddress } from '../../../common/interfaces/address.interface';
import { IMongoRepository } from './repository.abstract';
import { Reward, RewardDocument } from 'src/modules/rewards/entities/reward.entity';
import { IReward } from '../../interfaces/reward.interface'
import { DeliveryOrderDocument } from "../../../modules/delivery/entities/delivery-order.entity";
import { IDeliveryOrder } from "../../../modules/delivery/interfaces/delivery-order.interface";
import { IActionLogs } from '../../interfaces/action-log.interface';
import { ActionLogs, ActionLogsDocument } from '../entities/actionLog.entity';
import { RewardTransactionLog, RewardTransactionLogDocument } from '../entities/reward-transaction-log.entity';
import { IRewardTransactionLog } from '../../interfaces/reward.interface';
import { PrintJob, PrintJobDocument } from '../entities/print-job.entity';
import { Coupon, CouponDocument } from '../../../modules/coupons/entity/coupons.entity';
import { ICoupon, ICouponLogs } from '../../../common/interfaces/coupons.interface';
import { CouponLogsDocument, CouponsLogs } from '../../../modules/coupons/entity/coupons-logs.entity';
import { IBranchs, IRestaurant } from 'src/common/interfaces/common.interface';
import { Restaurant, RestaurantDocument } from '../entities/restaurant.entity';
import { Branch, BranchDocument } from '../entities/branch.entity';
import { Review, ReviewDocument } from '../../../modules/reviews/entities/review.entity';
import { IReview } from '../../interfaces/review.interface';
import { ReviewVisibility, ReviewVisibilityDocument } from '../../../modules/reviews/entities/review-visibility.entity';
import { IReviewVisibility } from '../../interfaces/review-visibility.interface';
import { OtpSessions, OtpSessionsDocument } from 'src/modules/auth/entity/otp-sessions.entity';
import { IOtpSessions } from 'src/common/interfaces/otp-sessions.interface';
import { UserAnalyticsMv, UserAnalyticsMvDocument } from '../entities/user-analytics-mv.entity';
export abstract class IMongoDBServices {
  abstract user: IMongoRepository<User, IUser, UserDocument>;
  abstract reward: IMongoRepository<Reward, IReward, RewardDocument>;
  abstract cart: IMongoRepository<Cart, ICart, CartDocument>;
  abstract coupon: IMongoRepository<Coupon, ICoupon, CouponDocument>;
  abstract couponlog: IMongoRepository<CouponsLogs, ICouponLogs, CouponLogsDocument>;
  abstract order: IMongoRepository<Order, IOrder, OrderDocument>;
  abstract address: IMongoRepository<Address, IAddress, AddressDocument>;
  abstract adminUser: IMongoRepository<AdminUser, IAdminUser, AdminUserDocument>;
  abstract lead: IMongoRepository<Lead, ILead, LeadDocument>;
  abstract deliveryOrder: IMongoRepository<DeliveryOrderDocument, IDeliveryOrder, IDeliveryOrder>;
  abstract actionLogs: IMongoRepository<ActionLogs, IActionLogs, ActionLogsDocument>;
  abstract rewardTransactionLog: IMongoRepository<RewardTransactionLog, IRewardTransactionLog, RewardTransactionLogDocument>;
  abstract printJob: IMongoRepository<PrintJob, any, PrintJobDocument>;
  abstract restaurant: IMongoRepository<Restaurant, IRestaurant, RestaurantDocument>;
  abstract branch: IMongoRepository<Branch, IBranchs, BranchDocument>;
  abstract review: IMongoRepository<Review, IReview, ReviewDocument>;
  abstract reviewVisibility: IMongoRepository<ReviewVisibility, IReviewVisibility, ReviewVisibilityDocument>;
  abstract otpSessions: IMongoRepository<OtpSessions, IOtpSessions, OtpSessionsDocument>;
  abstract userAnalyticsMv: IMongoRepository<UserAnalyticsMv, any, UserAnalyticsMvDocument>;
}