import { IsString, IsNotEmpty, IsOptional, IsBoolean, IsEmail, IsDateString } from 'class-validator';
import { UserTypeEnum } from '../../../common/enums/user.enum';
export class UserDto {
  @IsString()
  @IsOptional() // Make userId optional for creation, as it might be generated by the database
  userId: string;

  @IsString()
  @IsNotEmpty()
  firstName: string;

  @IsString()
  @IsOptional()
  lastName?: string;

  @IsEmail()
  @IsNotEmpty()
  email: string;

  @IsString()
  @IsNotEmpty()
  phoneNumber: string;

  @IsDateString()
  @IsOptional()
  birthday?: Date;

  @IsString()
  @IsNotEmpty()
  userType: UserTypeEnum;

  @IsString()
  @IsOptional()
  authProvider: string;

  @IsString()
  @IsOptional()
  restaurantId: string;

  @IsBoolean()
  @IsOptional()
  getPromotionalEmails?: boolean;

  @IsBoolean()
  @IsOptional()
  getPromotionalTexts?: boolean;
} 